del ..\ckt.lib
cl /I..\..\include /I..\dev /c acan.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c acaskq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c acsetp.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktaccpt.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktacct.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktacdum.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktask.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktaskaq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktasknq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktbindn.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktbkdum.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktclrbk.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktcrte.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktdelt.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktdest.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktdisto.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktdlti.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktdltm.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktdltn.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktdojob.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktdump.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktfbran.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktfdev.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktfnda.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktfndm.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktfnode.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktftask.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktgrnd.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c ckti2nod.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktic.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktinit.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktlnkeq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktload.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktmapn.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktmask.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktmcrt.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktmkcur.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktmknod.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktmkvol.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktmpar.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktnames.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktnewan.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktneweq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktnewn.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktnodn.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktnoise.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktntask.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktnum2n.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktop.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktparam.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktpmnam.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktpname.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktpzld.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktpzset.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktpzstr.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktsetap.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktsetbk.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktsetnp.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktsetup.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktsgen.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktsopt.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c ckttemp.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktterr.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c ckttroub.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c ckttrunc.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c ckttyplk.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c daskq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c dcoaskq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c dcop.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c dcosetp.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c dctaskq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c dctran.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c dctrcurv.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c dctsetp.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c distoan.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c dkerproc.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c dloadfns.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c dsetparm.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c naskq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c nevalsrc.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c ninteg.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c noisean.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c nsetparm.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c pzan.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c pzaskq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c pzsetp.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c sensaskq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c senssetp.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c tfanal.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c tfaskq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c tfsetp.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c tranaskq.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c traninit.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c transetp.c >> ..\..\msc.out
cl /I..\..\include /I..\dev /c cktsens.c >> ..\..\msc.out
lib ..\ckt.lib @response.lib >> ..\..\msc.out
