del ..\inp.lib
cl /I..\..\include /c ifeval.c >> ..\..\msc.out
cl /I..\..\include /c ifnewuid.c >> ..\..\msc.out
cl /I..\..\include /c inp2b.c >> ..\..\msc.out
cl /I..\..\include /c inp2c.c >> ..\..\msc.out
cl /I..\..\include /c inp2d.c >> ..\..\msc.out
cl /I..\..\include /c inp2dot.c >> ..\..\msc.out
cl /I..\..\include /c inp2e.c >> ..\..\msc.out
cl /I..\..\include /c inp2f.c >> ..\..\msc.out
cl /I..\..\include /c inp2g.c >> ..\..\msc.out
cl /I..\..\include /c inp2h.c >> ..\..\msc.out
cl /I..\..\include /c inp2i.c >> ..\..\msc.out
cl /I..\..\include /c inp2j.c >> ..\..\msc.out
cl /I..\..\include /c inp2k.c >> ..\..\msc.out
cl /I..\..\include /c inp2l.c >> ..\..\msc.out
cl /I..\..\include /c inp2m.c >> ..\..\msc.out
cl /I..\..\include /c inp2o.c >> ..\..\msc.out
cl /I..\..\include /c inp2q.c >> ..\..\msc.out
cl /I..\..\include /c inp2r.c >> ..\..\msc.out
cl /I..\..\include /c inp2s.c >> ..\..\msc.out
cl /I..\..\include /c inp2t.c >> ..\..\msc.out
cl /I..\..\include /c inp2u.c >> ..\..\msc.out
cl /I..\..\include /c inp2v.c >> ..\..\msc.out
cl /I..\..\include /c inp2w.c >> ..\..\msc.out
cl /I..\..\include /c inp2z.c >> ..\..\msc.out
cl /I..\..\include /c inpaname.c >> ..\..\msc.out
cl /I..\..\include /c inpapnam.c >> ..\..\msc.out
cl /I..\..\include /c inpcfix.c >> ..\..\msc.out
cl /I..\..\include /c inpdomod.c >> ..\..\msc.out
cl /I..\..\include /c inpdoopt.c >> ..\..\msc.out
cl /I..\..\include /c inpdpar.c >> ..\..\msc.out
cl /I..\..\include /c inperrc.c >> ..\..\msc.out
cl /I..\..\include /c inperror.c >> ..\..\msc.out
cl /I..\..\include /c inpeval.c >> ..\..\msc.out
cl /I..\..\include /c inpfindl.c >> ..\..\msc.out
cl /I..\..\include /c inpgmod.c >> ..\..\msc.out
cl /I..\..\include /c inpgtitl.c >> ..\..\msc.out
cl /I..\..\include /c inpgtok.c >> ..\..\msc.out
cl /I..\..\include /c inpgval.c >> ..\..\msc.out
cl /I..\..\include /c inpkmods.c >> ..\..\msc.out
cl /I..\..\include /c inplist.c >> ..\..\msc.out
cl /I..\..\include /c inplkmod.c >> ..\..\msc.out
cl /I..\..\include /c inpmkmod.c >> ..\..\msc.out
cl /I..\..\include /c inpmktmp.c >> ..\..\msc.out
cl /I..\..\include /c inppas1.c >> ..\..\msc.out
cl /I..\..\include /c inppas2.c >> ..\..\msc.out
cl /I..\..\include /c inppname.c >> ..\..\msc.out
cl /I..\..\include /c inpptree.c >> ..\..\msc.out
cl /I..\..\include /c inpsymt.c >> ..\..\msc.out
cl /I..\..\include /c inptyplk.c >> ..\..\msc.out
cl /I..\..\include /c ptfuncs.c >> ..\..\msc.out
cl /I..\..\include /c sperror.c >> ..\..\msc.out
cl /I..\..\include /c inpgstr.c >> ..\..\msc.out
lib ..\inp.lib @response.lib >> ..\..\msc.out
