cl /I..\..\..\include /c mos3.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3acld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3ask.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3conv.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3del.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3dest.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3dist.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3dset.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3ic.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3load.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3mask.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3mdel.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3mpar.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3noi.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3par.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3pzld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3sacl.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3set.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3sld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3sprt.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3sset.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3supd.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3temp.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos3trun.c >> ..\..\..\msc.out
lib ..\..\dev2.lib @response.lib >> ..\..\..\msc.out
