cl /I..\..\..\include /c cap.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capacld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capask.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capdel.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capdest.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capgetic.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capload.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capmask.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capmdel.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capmpar.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capparam.c >> ..\..\..\msc.out
cl /I..\..\..\include /c cappzld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capsacl.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capsetup.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capsload.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capsprt.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capsset.c >> ..\..\..\msc.out
cl /I..\..\..\include /c capsupd.c >> ..\..\..\msc.out
cl /I..\..\..\include /c captemp.c >> ..\..\..\msc.out
cl /I..\..\..\include /c captrunc.c >> ..\..\..\msc.out
lib ..\..\dev1.lib @response.lib >> ..\..\..\msc.out
