cl /I..\..\..\include /c b2.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2acld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2ask.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2cvtest.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2del.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2dest.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2eval.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2getic.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2ld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2mask.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2mdel.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2moscap.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2mpar.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2par.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2pzld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2set.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2temp.c >> ..\..\..\msc.out
cl /I..\..\..\include /c b2trunc.c >> ..\..\..\msc.out
lib ..\..\dev3.lib @response.lib >> ..\..\..\msc.out
