rem   WARNING: this script deletes all files and
rem   directories for Spice3f5.
rem   Hit ^C now if you do not want to do this.
rem
rem   You will have to hit 'y' for the "del *.*"
rem   commands that follow.
pause
del util\skeleton\*.*
del util\*.*
del notes\*.*
del conf\*.*
del src\unsuppo\*.*
del src\include\*.*
del src\bin\*.*
del src\lib\mac\*.*
del src\lib\mfbpc\*.*
del src\lib\ckt\*.*
del src\lib\sparse\*.*
del src\lib\misc\*.*
del src\lib\ni\*.*
del src\lib\mfb\*.*
del src\lib\dev\ltra\*.*
del src\lib\dev\isrc\*.*
del src\lib\dev\asrc\*.*
del src\lib\dev\vccs\*.*
del src\lib\dev\bsim2\*.*
del src\lib\dev\ind\*.*
del src\lib\dev\vsrc\*.*
del src\lib\dev\vcvs\*.*
del src\lib\dev\urc\*.*
del src\lib\dev\tra\*.*
del src\lib\dev\sw\*.*
del src\lib\dev\res\*.*
del src\lib\dev\mos6\*.*
del src\lib\dev\mos3\*.*
del src\lib\dev\mos2\*.*
del src\lib\dev\mos1\*.*
del src\lib\dev\mes\*.*
del src\lib\dev\jfet\*.*
del src\lib\dev\disto\*.*
del src\lib\dev\dio\*.*
del src\lib\dev\csw\*.*
del src\lib\dev\ccvs\*.*
del src\lib\dev\cccs\*.*
del src\lib\dev\cap\*.*
del src\lib\dev\bsim1\*.*
del src\lib\dev\bjt\*.*
del src\lib\dev\*.*
del src\lib\fte\*.*
del src\lib\inp\*.*
del src\lib\hlp\*.*
del src\lib\cp\*.*
del src\lib\*.*
del src\*.*
del man\man3\*.*
del man\man1\*.*
del man\man5\*.*
del man\*.*
del examples\*.*
del lib\helpdir\*.*
del lib\scripts\*.*
del lib\*.*
del *.*
rmdir util\skeleton
rmdir util
rmdir notes
rmdir conf
rmdir src\unsuppo
rmdir src\include
rmdir src\bin
rmdir src\lib\mac
rmdir src\lib\mfbpc
rmdir src\lib\ckt
rmdir src\lib\sparse
rmdir src\lib\misc
rmdir src\lib\ni
rmdir src\lib\mfb
rmdir src\lib\dev\ltra
rmdir src\lib\dev\isrc
rmdir src\lib\dev\asrc
rmdir src\lib\dev\vccs
rmdir src\lib\dev\bsim2
rmdir src\lib\dev\ind
rmdir src\lib\dev\vsrc
rmdir src\lib\dev\vcvs
rmdir src\lib\dev\urc
rmdir src\lib\dev\tra
rmdir src\lib\dev\sw
rmdir src\lib\dev\res
rmdir src\lib\dev\mos6
rmdir src\lib\dev\mos3
rmdir src\lib\dev\mos2
rmdir src\lib\dev\mos1
rmdir src\lib\dev\mes
rmdir src\lib\dev\jfet
rmdir src\lib\dev\disto
rmdir src\lib\dev\dio
rmdir src\lib\dev\csw
rmdir src\lib\dev\ccvs
rmdir src\lib\dev\cccs
rmdir src\lib\dev\cap
rmdir src\lib\dev\bsim1
rmdir src\lib\dev\bjt
rmdir src\lib\dev
rmdir src\lib\fte
rmdir src\lib\inp
rmdir src\lib\hlp
rmdir src\lib\cp
rmdir src\lib
rmdir src
rmdir man\man3
rmdir man\man1
rmdir man\man5
rmdir man
rmdir examples
rmdir lib\helpdir
rmdir lib\scripts
rmdir lib
rem
rem   All done removing Spice
