cl /I..\..\..\include /c dio.c >> ..\..\..\msc.out
cl /I..\..\..\include /c dioacld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c dioask.c >> ..\..\..\msc.out
cl /I..\..\..\include /c dioconv.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diodel.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diodest.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diodisto.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diodset.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diogetic.c >> ..\..\..\msc.out
cl /I..\..\..\include /c dioload.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diomask.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diomdel.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diompar.c >> ..\..\..\msc.out
cl /I..\..\..\include /c dionoise.c >> ..\..\..\msc.out
cl /I..\..\..\include /c dioparam.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diopzld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diosacl.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diosetup.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diosload.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diosprt.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diosset.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diosupd.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diotemp.c >> ..\..\..\msc.out
cl /I..\..\..\include /c diotrunc.c >> ..\..\..\msc.out
lib ..\..\dev2.lib @response.lib >> ..\..\..\msc.out
