cl /I..\..\..\include /c mes.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesacl.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesask.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesdel.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesdest.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesdisto.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesdset.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesgetic.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesload.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesmask.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesmdel.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesmpar.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesnoise.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mesparam.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mespzld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c messetup.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mestemp.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mestrunc.c >> ..\..\..\msc.out
lib ..\..\dev3.lib @response.lib >> ..\..\..\msc.out
