cl /I..\..\..\include /c mos2.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2acld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2ask.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2conv.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2del.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2dest.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2dist.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2dset.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2ic.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2load.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2mdel.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2mpar.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2noi.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2par.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2pzld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2sacl.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2set.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2sld.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2sprt.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2sset.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2supd.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2temp.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2trun.c >> ..\..\..\msc.out
cl /I..\..\..\include /c mos2mask.c >> ..\..\..\msc.out
lib ..\..\dev2.lib @response.lib >> ..\..\..\msc.out
